version: '3.7'

services:
  backend:
    build:
      context: ../backend/zillow-backend
      dockerfile: ../../docker/Dockerfile.backend
    container_name: laravel-backend
    working_dir: /var/www
    volumes:
      - ../backend/zillow-backend:/var/www
    networks:
      - app-network
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=zillow
      - DB_USERNAME=root
      - DB_PASSWORD=Okothbravon@2

  frontend:
    build:
      context: ../frontend/keja-frontend
      dockerfile: ../../docker/Dockerfile.frontend
    container_name: angular-frontend
    
    ports:
      - "8080:8080"
    networks:
      - app-network


  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Okothbravon@2
      MYSQL_DATABASE: zillow
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge